# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ysgol Bethel
tagline:          'Dogfennau / Documents'
description:      'Contents'
url:              http://www.xyz.com

author:
  name:           'YB'
  url:            ''

paginate:         5

# Custom vars
version:          2.0.0

#github:
#  repo:           https://github.com/poole/lanyon
